name: Clear All Caches

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear all caches
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Starting cache cleanup...")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            
            console.log(`Found ${caches.data.actions_caches.length} caches`)
            
            for (const cache of caches.data.actions_caches) {
              console.log(`Deleting cache: ${cache.key} (ID: ${cache.id})`)
              await github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            console.log("Cache cleanup completed!")
